@startuml

left to right direction
actor User as user
actor Admin as admin

rectangle "Blog System" {
    usecase "View All Articles" as UC_ViewArticles
    usecase "View Single Article" as UC_ViewArticle
    usecase "Add comments" as UC_AddComments

    usecase "Crud articles" as UC_CrudArticles
    usecase "Crud categories" as UC_CrudCategories
    usecase "Crud tags" as UC_CrudTags

}


user -- UC_ViewArticle
user -- UC_ViewArticles
user -- UC_AddComments

admin -- UC_CrudArticles
admin -- UC_CrudCategories
admin -- UC_CrudTags


@enduml
