@startuml

left to right direction
actor User as user
actor Admin as admin

rectangle "Blog System" {
    usecase "View All Articles" as UC_ViewArticles
    usecase "View Single Article" as UC_ViewArticle
    usecase "Edit an Article" as UC_EditArticle
    usecase "Create an Article" as UC_CreateArticle
}

user --> UC_ViewArticles
user --> UC_ViewArticle

admin --> UC_ViewArticles
admin --> UC_ViewArticle
admin --> UC_EditArticle
admin --> UC_CreateArticle

@enduml
